DLS_Project/Models/ErrorViewModel.cs
using System;

namespace DLS_Project.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DLS_Project/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DLS_Project.Models;
using BusinessLayer;
using PresentationLayer;

namespace DLS_Project.Controllers
{
    public class HomeController : Controller
    {
        private DataManager _dataManager;
        private ServicesManager _serviceManager;

        public HomeController(DataManager dataManager)
        {
            _dataManager = dataManager;
            _serviceManager = new ServicesManager(_dataManager);
        }

        public IActionResult Index()
        {
            var dirs = _serviceManager.DirService.TransitDirectoriesToView();
            return View(dirs);
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DLS_Project/Controllers/PageController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BusinessLayer;
using PresentationLayer;
using PresentationLayer.ViewModels;
using static DataLayer.Enums.PageEnums;

namespace DLS_Project.Controllers
{
    public class PageController : Controller
    {
        private DataManager _dataManager;
        private ServicesManager _servicesManager;

        public PageController(DataManager dataManager)
        {
            _dataManager = dataManager;
            _servicesManager = new ServicesManager(dataManager);
        }
        
        public IActionResult Index(int pageId, PageType pageType)
        {
            PageViewModel viewModel;
            switch (pageType)
            {
                case PageType.Directory:
                    viewModel = _servicesManager.DirService.TransitDirectoryToView(pageId);
                    break;
                case PageType.Material:
                    viewModel = _servicesManager.MatService.TransitMaterialToView(pageId);
                    break;
                default:
                    viewModel = null;
                    break;
            }
            ViewBag.PageType = pageType;
            return View(viewModel);
        }

        [HttpGet]
        public IActionResult PageEditor(int pageId, PageType pageType, int directoryId = 0)
        {
            PageViewModel viewModel;
            switch (pageType)
            {
                case PageType.Directory:
                    if (pageId != 0)
                        viewModel = _servicesManager.DirService.GetDirectoryEditModel(pageId);
                    else
                        viewModel = _servicesManager.DirService.CreateNewDirectoryModel();
                    break;
                case PageType.Material:
                    if (pageId != 0)
                        viewModel = _servicesManager.MatService.GetMaterialEditModel(pageId);
                    else
                        viewModel = _servicesManager.MatService.CreateNewMaterialEditModel(directoryId);
                    break;
                default:
                    viewModel = null;
                    break;
            }
            ViewBag.PageType = pageType;
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult SaveDirectory(DirectoryViewModel model)
        {
            _servicesManager.DirService.SaveDirectoryEditModel(model);            
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public IActionResult SaveMaterial(MaterialViewModel model)
        {
            _servicesManager.MatService.SaveMaterialToDb(model);
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public IActionResult DeleteDirectory(int directoryId)
        {
            _servicesManager.DirService.DeleteDirectoryFromDb(directoryId);
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public IActionResult DeleteMaterial(int materialId)
        {
            _servicesManager.MatService.DeleteMaterialFromDb(materialId);
            return RedirectToAction("Index", "Home");
        }
    }
}

DLS_Project/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

DLS_Project/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

DLS_Project/Views/Home/Index.cshtml
@using PresentationLayer.ViewModels;
@using DataLayer.Enums;

@model List<DirectoryViewModel>

@{
    ViewData["Title"] = "Home Page";
}

<div class="row">
    <div class="col-md-6">
        <ul>
            @foreach (var item in Model)
            {
                <li>
                    <h2>
                        <a asp-action="Index" asp-controller="Page"
                           asp-route-pageId="@item.Directory.Id"
                           asp-route-pageType="@PageEnums.PageType.Directory">
                            @item.Directory.Title
                        </a>
                        |
                        <small>
                            <a asp-action="PageEditor" asp-controller="Page"
                               asp-route-pageId="@item.Directory.Id"
                               asp-route-pageType="@PageEnums.PageType.Directory">
                                EditDirectory
                            </a>
                        </small>
                        |
                        <small>
                            <a asp-action="DeleteDirectory" asp-controller="Page"
                               asp-route-directoryId="@item.Directory.Id"
                            >
                                DeleteDirectory
                            </a>
                        </small>
                        |
                    </h2>                                                          
                    <ul>
                        @if (item.Materials != null)
                        {
                            foreach (var sub in item.Materials)
                            {
                                <li>
                                    <a asp-action="Index" asp-controller="Page"
                                       asp-route-pageId="@sub.Material.Id"
                                       asp-route-pageType="@PageEnums.PageType.Material">
                                        @sub.Material.Title
                                    </a>
                                    |
                                    <a asp-action="PageEditor" asp-controller="Page"
                                       asp-route-pageId="@sub.Material.Id"
                                       asp-route-directoryId="@item.Directory.Id"
                                       asp-route-pageType="@PageEnums.PageType.Material">
                                        EditMaterial
                                    </a>
                                    |
                                    <a asp-action="DeleteMatrial" asp-controller="Page"
                                       asp-route-directoryId="@sub.Material.Id">
                                        DeleteMaterial
                                    </a>
                                    |
                                </li>
                            }
                    <li>
                        <a asp-action="PageEditor" asp-controller="Page"
                           asp-route-pageId="0"
                           asp-route-directoryId="@item.Directory.Id"
                           asp-route-pageType="@PageEnums.PageType.Material">
                            --> CreateMaterial
                        </a>
                    </li>
                        }
                    </ul>
                </li>
            }
            <li>
                <a asp-action="PageEditor" asp-controller="Page"
                   asp-route-pageId="0"
                   asp-route-pagetype="@PageEnums.PageType.Directory">
                    --> CreateDirectory
                </a>
            </li>
        </ul>
    </div>
</div>

DLS_Project/Views/Page/Index.cshtml
@using PresentationLayer.ViewModels;
@using DataLayer.Enums;

@model PageViewModel

@if (Model is DirectoryViewModel)
{
    var currentModel = (DirectoryViewModel)Model;
    <h1>@currentModel.Directory.Title</h1>
    <p>@Html.Raw(currentModel.Directory.Html)</p>
    <ul>
        @if (currentModel.Materials != null)
        {
            foreach (var sub in currentModel.Materials)
            {
                <li>
                    <a asp-action="Index" asp-controller="Page" 
                       asp-route-pageId="@sub.Material.Id" asp-route-pageType="@PageEnums.PageType.Material">
                        @sub.Material.Title
                    </a>
                </li>
            }
            
        }
    </ul>
}
else if (Model is MaterialViewModel)
{
    var currentModel = (MaterialViewModel)Model;
    <h1>@currentModel.Material.Title</h1>
    <p>@Html.Raw(currentModel.Material.Html)</p>
    @if(currentModel.NextMaterial != null)
    {
        <ul>
            <li>
                <a asp-action="Index" asp-controller="Page"
                   asp-route-pageId="@currentModel.NextMaterial.Id"
                   asp-route-PageType="@PageEnums.PageType.Material">
                    @currentModel.NextMaterial.Title
                </a>
            </li>
        </ul>
    }
}

DLS_Project/Views/Page/PageEditor.cshtml
@using PresentationLayer.ViewModels;
@using DataLayer.Enums;

@model PageViewModel

@if (Model is DirectoryViewModel)
{
    var currentModel = (DirectoryViewModel)Model;

    <form action="/Page/SaveDirectory" method="post">
        <input type="hidden" value="@ViewBag.PageType" name="PageType" />
        <input type="hidden" value="@currentModel.Id" name="Id" />
        <h1>Save/Edit Directory</h1>
        <div class="form-group">
            <label for="Title">Title:</label>
            <input name="Title" value="@currentModel.Title" class="form-control" />
        </div>
        <div class="form-group">
            <label for="Html">Htmls:</label>
            <input name="Html" value="@currentModel.Html" class="form-control" />
        </div>
        <div class="form-group">
            <input type="submit" class="btn btn-success" />
        </div>
    </form>
}
else if (Model is MaterialViewModel)
{
    var currentModel = (MaterialViewModel)Model;

<form action="/Page/SaveDirectory" method="post">
    <input type="hidden" value="@ViewBag.PageType" name="PageType" />
    <input type="hidden" value="@currentModel.Id" name="Id" />
    <input type="hidden" value="@currentModel.DirectoryId" name="Id" />
    <h1>Save/Edit Material</h1>
    <div class="form-group">
        <label for="Title">Title:</label>
        <input name="Title" value="@currentModel.Title" class="form-control" />
    </div>
    <div class="form-group">
        <label for="Html">Htmls:</label>
        <input name="Html" value="@currentModel.Html" class="form-control" />
    </div>
    <div class="form-group">
        <input type="submit" class="btn btn-success" />
    </div>
</form>
}

DLS_Project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DLS_Project</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">DLS_Project</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2021 - DLS_Project</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>